# github sponsors configuration
# https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button

github: fentbuscoding
# patreon: fentbuscoding
# ko_fi: fentbuscoding
# custom: ['https://www.buymeacoffee.com/fentbuscoding']
